version: '3.8' # Versión de la sintaxis de Docker Compose

services:
  web:
    build: . # Construye la imagen usando el Dockerfile en el directorio actual
    container_name: flask_login_app # Nombre amigable para el contenedor
    ports:
      - "5000:5000" # Mapea el puerto 5000 del host al puerto 5000 del contenedor
    volumes:
      - .:/app # Monta el directorio actual del host al /app del contenedor
                # Esto permite que los cambios en tu código local se reflejen
                # instantáneamente en el contenedor sin reconstruir la imagen.
                # También es donde se creará database.db en tu máquina local.
    environment:
      # Puedes definir variables de entorno aquí, por ejemplo:
      FLASK_APP: app.py
      FLASK_ENV: development # Para desarrollo (Flask 2.x recomienda esto en lugar de debug=True en app.run)
      # No coloques app.secret_key aquí directamente por seguridad en producción.
      # Para desarrollo, os.urandom(24) en app.py está bien.
    # network_mode: host # Descomentar si quieres que el contenedor use directamente la red del host
                        # Puede simplificar el acceso, pero es menos aislado.
    # restart: always # Descomentar para reiniciar el contenedor automáticamente si falla